//
// Created by 水瀬あくあ on 2021/4/25.
//

#ifndef CPP_MUDUO_LEARNING_DEFINE_H
#define CPP_MUDUO_LEARNING_DEFINE_H

#define MAX_LINE 1024
#define MAX_EVENTS 500
#define MAX_LISTEN_FD 5
#define LISTEN_PORT 6868

#define SOCKET_CREATE_ERROR -10
#define EPOLL_ERROR -11

#endif //CPP_MUDUO_LEARNING_DEFINE_H
